spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/campus_flow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=shri27
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true