# spring.application.name=demo
# spring.datasource.url=jdbc:mysql://localhost:3306/campus_flow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=shri27
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.application.name=demo
# 1. PUBLIC RAILWAY DATABASE URL
spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:21392/railway?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
# 2. RAILWAY CREDENTIALS
spring.datasource.username=root
spring.datasource.password=bIUudbaoXQdqqJXurBLKszOpthGrWYmx
# 3. EXPLICIT MYSQL DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 4. HIBERNATE AUTO-MAPPING CONFIGURATIONS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect